name: Release the refinery binaries
on:
  push:
    branches:
      - 'shain/**'
  workflow_call:
    inputs:
      username:
        os: 'linux'
        arch: 'x86_64'
        buildid: '33999-randy'
jobs:
  go-build:
    runs-on: ubuntu-latest, macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Go build
        run |
          GOOS=${{ inputs.os }} \
          GOARCH=${{ inputs.arch }} \
          go build -ldflags "-X main.BuildID=${{ inputs.buildid }}" \
          -o $GOPATH/bin/refinery-${{ inputs.os }}-${{ inputs.arch }} \
          ./cmd/refinery



            # GOOS=<< parameters.fos >> \
            # GOARCH=<< parameters.arch >> \
            # go build -ldflags "-X main.BuildID=${CIRCLE_TAG:-${CIRCLE_SHA1:0:7}}" \
            # -o $GOPATH/bin/refinery-<< parameters.os >>-<< parameters.arch >> \
            # ./cmd/refinery