name: Release the refinery binaries
on:
  push:
    branches:
      - 'shain/**'
  pull_request:
    branches_ignore:
      - main

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Go build
        run: echo FUUUUPPPPPMFFF
