name: Release the refinery binaries
on:
  push:
    branches:
      - 'shain/**'
  # workflow_call:
  #   inputs:
  #     username:
  #       os: 'linux'
  #       arch: 'x86_64'
  #       buildid: '33999-randy'
jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Go build
        run: echo FUUUUPPPPPMFFF
